import type { ModelDocumentInput } from "@/lib/model-spec";

const printDefaults = {
  buildVolume: [256, 256, 256] as [number, number, number],
  autoCenter: true,
  placeOnBed: true,
};

export const DEMO_MODELS = {
  "type-specimen": {
    version: "1.0",
    name: "Type specimen",
    description: "A fully spec-driven Google Font wordmark with printable styling and live dimensions.",
    units: "mm",
    root: {
      kind: "shape",
      id: "wordmark",
      source: {
        type: "text",
        text: "Printa",
        font: "Space Grotesk",
        size: 42,
        depth: 6,
        bevel: 0.8,
        bevelSegments: 4,
        curveSegments: 12,
        bevelSide: "both",
        smoothNormals: true,
        textCase: "original",
        weight: "bold",
        italic: false,
        underline: false,
      },
      modifiers: [],
      material: "pla-orange",
    },
    print: printDefaults,
    display: {
      floor: true,
      grid: true,
      dimensions: { visible: true, width: true, height: true, offset: 9, precision: 1 },
    },
    metadata: { family: "text", font: "Space Grotesk" },
  },
  "contour-spiral-vase": {
    version: "1.0",
    name: "Contour spiral vase",
    description: "A rounded vessel with fine helical ribs inspired by layered ceramic forms.",
    units: "mm",
    root: {
      kind: "shape",
      id: "vessel",
      source: {
        type: "revolve",
        profile: [[31, 0], [35, 18], [41, 52], [37, 88], [31, 122], [27, 145]],
        segments: 192,
        profileSegments: 120,
        wall: 2.2,
        bottomCap: true,
        bottomThickness: 3,
        topCap: false,
        topThickness: 2.4,
        interpolation: "catmull-rom",
        axis: "z",
      },
      modifiers: [
        { type: "radialWave", amplitude: 1.7, count: 18, phaseDeg: 0, axialTurns: 0 },
        { type: "twist", angleDeg: 230, start: 0, end: 1 },
      ],
      material: "pla-matte",
    },
    print: printDefaults,
    metadata: { family: "vase", supportFree: true },
  },
  "zenith-twist": {
    version: "1.0",
    name: "Zenith twist vase",
    description: "A tall three-lobed vase with a strong continuous spiral.",
    units: "mm",
    root: {
      kind: "shape",
      id: "zenith",
      source: {
        type: "revolve",
        profile: [[24, 0], [27, 20], [29, 55], [28, 105], [25, 150], [24, 172]],
        segments: 180,
        profileSegments: 130,
        wall: 2.4,
        bottomCap: true,
        bottomThickness: 3.2,
        topCap: false,
        topThickness: 2.4,
        interpolation: "catmull-rom",
        axis: "z",
      },
      modifiers: [
        { type: "radialWave", amplitude: 7.2, count: 3, phaseDeg: 90, axialTurns: 0 },
        { type: "twist", angleDeg: 185, start: 0, end: 1 },
        { type: "taper", from: 1.04, to: 0.84, easing: "smoothstep" },
      ],
      material: "resin",
    },
    print: printDefaults,
    metadata: { family: "vase", lobes: 3 },
  },
  "fluted-bud-vase": {
    version: "1.0",
    name: "Fluted bud vase",
    description: "A bulbous lathed profile with sixteen flowing flutes.",
    units: "mm",
    root: {
      kind: "shape",
      id: "bud",
      source: {
        type: "revolve",
        profile: [[25, 0], [36, 22], [45, 60], [37, 96], [24, 122], [28, 144]],
        segments: 192,
        profileSegments: 112,
        wall: 2.1,
        bottomCap: true,
        bottomThickness: 2.8,
        topCap: false,
        topThickness: 2.4,
        interpolation: "catmull-rom",
        axis: "z",
      },
      modifiers: [
        { type: "radialWave", amplitude: 2.8, count: 16, phaseDeg: 0, axialTurns: 0 },
        { type: "twist", angleDeg: 58, start: 0.05, end: 1 },
      ],
      material: "pla-matte",
    },
    print: printDefaults,
    metadata: { family: "vase", flutes: 16 },
  },
  "ripple-column-vase": {
    version: "1.0",
    name: "Ripple column vase",
    description: "A marble-like stacked ripple silhouette made from one revolved profile.",
    units: "mm",
    root: {
      kind: "shape",
      id: "ripple-column",
      source: {
        type: "revolve",
        profile: [[29, 0], [37, 12], [31, 29], [43, 46], [32, 65], [43, 84], [31, 103], [38, 120], [29, 134]],
        segments: 180,
        profileSegments: 144,
        wall: 2.5,
        bottomCap: true,
        bottomThickness: 3.2,
        topCap: true,
        topThickness: 3.2,
        interpolation: "catmull-rom",
        axis: "z",
      },
      modifiers: [
        { type: "radialWave", amplitude: 1.2, count: 5, phaseDeg: 0, axialTurns: 0 },
        { type: "twist", angleDeg: 32, start: 0, end: 1 },
      ],
      material: "pla-silk",
    },
    print: printDefaults,
    metadata: { family: "vase", profile: "stacked-ripple" },
  },
  "spline-petal-dish": {
    version: "1.0",
    name: "Spline petal dish",
    description: "A custom Bézier outline extruded into a printable shallow dish blank.",
    units: "mm",
    root: {
      kind: "shape",
      id: "petal",
      source: {
        type: "extrude",
        depth: 8,
        bevel: 1.2,
        bevelSegments: 5,
        curveSegments: 20,
        direction: [0, 0, 1],
        path: {
          commands: [
            { op: "move", to: [0, 44] },
            { op: "bezier", control1: [24, 48], control2: [48, 28], to: [38, 4] },
            { op: "bezier", control1: [48, -18], control2: [25, -45], to: [0, -35] },
            { op: "bezier", control1: [-25, -45], control2: [-48, -18], to: [-38, 4] },
            { op: "bezier", control1: [-48, 28], control2: [-24, 48], to: [0, 44] },
            { op: "close" },
          ],
          holes: [],
        },
      },
      modifiers: [
        { type: "twist", angleDeg: 9, start: 0, end: 1 },
      ],
      material: "resin",
    },
    print: printDefaults,
    metadata: { family: "custom-curve" },
  },
  "primitive-totem": {
    version: "1.0",
    name: "Primitive totem",
    description: "A layered assembly of cylinders, toruses, and a tapered crown.",
    units: "mm",
    root: {
      kind: "assembly",
      id: "totem",
      operation: "merge",
      modifiers: [],
      children: [
        {
          kind: "shape",
          id: "core",
          source: { type: "primitive", shape: "cylinder", radius: 18, height: 72, segments: 96 },
          modifiers: [{ type: "axialWave", amplitude: 2.2, cycles: 3, phaseDeg: 0 }],
          material: "pla-orange",
        },
        {
          kind: "repeat",
          id: "rings",
          count: 4,
          modifiers: [],
          step: { translate: [0, 0, 18], rotate: [0, 0, 17], scale: 0.94 },
          child: {
            kind: "shape",
            id: "ring",
            source: { type: "primitive", shape: "torus", radius: 21, tube: 2.4, segments: 96 },
            modifiers: [],
          },
        },
        {
          kind: "shape",
          id: "crown",
          source: { type: "primitive", shape: "cone", radiusBottom: 17, radiusTop: 6, height: 26, segments: 96 },
          modifiers: [{ type: "radialWave", amplitude: 1.3, count: 8, phaseDeg: 0, axialTurns: 0 }],
          transform: { translate: [0, 0, 70], rotate: [0, 0, 0], scale: 1 },
        },
      ],
    },
    print: printDefaults,
    metadata: { family: "assembly" },
  },
  "water-ripple-tile": {
    version: "1.0",
    name: "Water ripple tile",
    description: "A frozen printable water simulation with three interacting drops.",
    units: "mm",
    root: {
      kind: "shape",
      id: "water",
      source: {
        type: "water",
        width: 112,
        depth: 88,
        base: 4,
        resolution: 64,
        steps: 34,
        damping: 0.989,
        drops: [
          { x: -22, y: -8, radius: 6, amplitude: 7 },
          { x: 20, y: 12, radius: 7, amplitude: -5.5 },
          { x: 4, y: -24, radius: 5, amplitude: 4.5 },
        ],
      },
      modifiers: [],
      material: "petg",
    },
    print: printDefaults,
    metadata: { family: "simulation", solver: "damped-wave" },
  },
  "cloth-drape-study": {
    version: "1.0",
    name: "Cloth drape study",
    description: "A deterministic Verlet cloth simulation pinned at four corners over a sphere.",
    units: "mm",
    root: {
      kind: "shape",
      id: "cloth",
      source: {
        type: "cloth",
        width: 112,
        depth: 112,
        thickness: 1.4,
        resolution: 30,
        steps: 115,
        startHeight: 46,
        gravity: 0.2,
        constraintIterations: 5,
        pins: "corners",
        collider: { type: "sphere", center: [0, 0, 4], radius: 27 },
      },
      modifiers: [{ type: "noise", amplitude: 0.35, scale: 14, seed: 7 }],
      material: "resin",
    },
    print: printDefaults,
    metadata: { family: "simulation", solver: "verlet-cloth" },
  },
  "cellular-lattice": {
    version: "1.0",
    name: "Voronoi cellular lattice",
    description: "A seeded nearest-neighbour cellular frame for lightweight structural infill.",
    units: "mm",
    root: {
      kind: "shape",
      id: "cellular-frame",
      source: {
        type: "cellular",
        width: 60,
        depth: 54,
        height: 72,
        cellSize: 18,
        strutDiameter: 2.2,
        jitter: 0.64,
        neighbors: 3,
        seed: 19,
        radialSegments: 8,
      },
      modifiers: [],
      material: "petg",
    },
    print: printDefaults,
    metadata: { family: "lattice", pattern: "cellular" },
  },
  "organic-coral": {
    version: "1.0",
    name: "Organic coral growth",
    description: "A deterministic branching growth system with tapered printable limbs.",
    units: "mm",
    root: {
      kind: "shape",
      id: "coral-growth",
      source: {
        type: "organic",
        width: 72,
        depth: 72,
        height: 100,
        trunkDiameter: 7,
        levels: 4,
        branching: 2,
        angleDeg: 34,
        twistDeg: 137.5,
        taper: 0.72,
        seed: 11,
        radialSegments: 9,
      },
      modifiers: [],
      material: "resin",
    },
    print: printDefaults,
    metadata: { family: "organic", pattern: "branching-coral" },
  },
  "layered-contour-lamp": {
    version: "1.0",
    name: "Layered contour lamp",
    description: "A rounded triangular ring grown into cellular, inset, progressively twisted layers.",
    units: "mm",
    root: {
      kind: "shape",
      id: "layered-shade",
      source: {
        type: "extrude",
        depth: 2.6,
        bevel: 0,
        bevelSegments: 1,
        curveSegments: 5,
        direction: [0, 0, 1],
        path: {
          commands: [
            { op: "move", to: [0, 42] },
            { op: "bezier", control1: [30, 43], control2: [47, 24], to: [42, -5] },
            { op: "bezier", control1: [38, -32], control2: [20, -38], to: [0, -36] },
            { op: "bezier", control1: [-20, -38], control2: [-38, -32], to: [-42, -5] },
            { op: "bezier", control1: [-47, 24], control2: [-30, 43], to: [0, 42] },
            { op: "close" },
          ],
          holes: [[
            { op: "move", to: [0, 30] },
            { op: "bezier", control1: [20, 31], control2: [33, 17], to: [30, -4] },
            { op: "bezier", control1: [27, -22], control2: [14, -27], to: [0, -25] },
            { op: "bezier", control1: [-14, -27], control2: [-27, -22], to: [-30, -4] },
            { op: "bezier", control1: [-33, 17], control2: [-20, 31], to: [0, 30] },
            { op: "close" },
          ]],
        },
      },
      modifiers: [
        { type: "voronoi", amplitude: 0.55, scale: 22, seed: 7, mode: "ridges", contrast: 1.5 },
        { type: "step", levels: 6, axis: "z", distance: 5.4, inset: 1.5, twistDeg: 4.5 },
        { type: "array", count: 2, translate: [0, 0, 2.2], rotate: [0, 0, 10], scale: 0.98 },
      ],
      material: "pla-silk",
    },
    print: printDefaults,
    metadata: { family: "lampshade", pattern: "layered-contour" },
  },
} as const satisfies Record<string, ModelDocumentInput>;

export type DemoModelId = keyof typeof DEMO_MODELS;

export const DEMO_MODEL_CARDS = Object.entries(DEMO_MODELS).map(([id, model]) => ({
  id: id as DemoModelId,
  name: model.name,
  description: model.description,
  family: String(model.metadata.family),
}));

export function getDemoModel(id: string | null | undefined) {
  if (!id || !(id in DEMO_MODELS)) return null;
  return DEMO_MODELS[id as DemoModelId];
}
