/**
 * Bake the committed places.
 *
 * Places carry their captured ground with them, so the models on the site
 * build offline and identically every time. This regenerates that data into
 * `lib/place-library.generated.ts`; run it when the roster in
 * `lib/place-library.ts` changes, not on every build.
 *
 *   npm run bake:places
 */
import { writeFileSync } from "node:fs";
import { bakePlace } from "../lib/place-bake";
import { PLACES } from "../lib/place-library";

const apiKey = process.env.GOOGLE_MAPS_API_KEY ?? "";

async function main() {
  const baked: Record<string, unknown> = {};

  for (const place of PLACES) {
    const started = Date.now();
    process.stdout.write(`  ${place.slug} (${place.capture}) … `);
    try {
      const result = await bakePlace({
        lat: place.lat,
        lng: place.lng,
        radiusM: place.radiusM,
        capture: place.capture,
        label: place.name,
        apiKey,
      });
      baked[place.slug] = {
        surface: result.surface,
        ...(result.footprints ? { footprints: result.footprints } : {}),
        ...(result.roads ? { roads: result.roads } : {}),
      };
      const size = JSON.stringify(baked[place.slug]).length;
      console.log(`${result.note} — ${(size / 1024).toFixed(0)}KB in ${((Date.now() - started) / 1000).toFixed(1)}s`);
    } catch (error) {
      console.log(`FAILED: ${(error as Error).message}`);
      process.exitCode = 1;
    }
  }

  const header = `// Generated by scripts/bake-places.ts — do not edit by hand.\n`
    + `// Captured ground and outlines for the places in lib/place-library.ts.\n\n`;
  writeFileSync(
    "lib/place-library.generated.ts",
    `${header}export const BAKED_PLACES = ${JSON.stringify(baked, null, 0)} as const;\n`,
  );
  console.log(`\nWrote lib/place-library.generated.ts (${Object.keys(baked).length} places)`);
}

await main();
